FROM openjdk:17-oracle
EXPOSE 8443
ADD SecondFlowApp.jar target/app.jar
RUN bash -c 'touch target/app.jar'
ENTRYPOINT ["java","-jar","-Dspring.profiles.active=local","target/app.jar","--spring.datasource.url=jdbc:mysql://192.168.23.93/miBaseDatos"]
